version: '3'
services:
  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  people_and_places:
    build:
      context: .
    restart: on-failure
    depends_on:
      - db
    volumes:
      # Add the absolute path
      - /data/:/people_and_places/data/
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
